name: kilimosalama
description: Food security Project
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble_bottom_bar: ^1.2.0
  curved_navigation_bar: ^0.3.2
  google_fonts: ^0.3.9
  local_auth: ^0.6.1
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  getflutter: ^1.0.8
  cloud_firestore: ^0.13.5
  slimy_card: ^1.0.4
  http: ^0.12.0+4
  intl: ^0.16.1
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  weather: ^0.9.5
  firebase_storage: ^3.1.3
  firebase_core: ^0.4.4+2
  firebase_analytics: ^5.0.11
  google_sign_in: ^4.4.4
  open_iconic_flutter: ^0.3.0
  beauty_textfield: ^0.0.1
  tflite: ^1.0.5
  image_picker: ^0.6.6+1
  cached_network_image: ^2.2.0+1
  geolocator: ^5.3.2+2
  fluttertoast: ^3.1.3
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.4+1
  cloud_functions: ^0.5.0
  



  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ 
    # - assets/icon.png  #enables us to use anything in this folder
    - local_json/person.json  #enables us to use anything in this folder

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Ubuntu
  #     fonts:
  #       - asset: fonts/Ubuntu-Light.ttf 
        # - asset: fonts/Ubuntu-Light.ttf

    
  

        
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

