name: kilimosalama
description: Food security Project
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble_bottom_bar: ^2.0.0
  curved_navigation_bar: ^1.0.3
  google_fonts: ^2.3.0
  local_auth: ^1.1.11
  firebase_auth: ^3.3.8
  firebase_database: ^9.0.7
  getflutter: ^1.0.8
  cloud_firestore: ^3.1.9
  slimy_card: ^1.0.4
  http: ^0.13.4
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  weather: ^2.0.1
  firebase_storage: ^10.2.8
  firebase_core: ^1.12.0
  firebase_analytics: ^9.1.1
  google_sign_in: ^5.3.1
  open_iconic_flutter: ^0.3.0
  beauty_textfield: ^0.0.1
  tflite: ^1.1.2
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.0
  geolocator: ^8.0.5
  fluttertoast: ^8.0.9
  firebase_messaging: ^11.2.7
  flutter_local_notifications: ^9.5.3+1
  cloud_functions: ^3.2.8
  



  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ 
    # - assets/icon.png  #enables us to use anything in this folder
    - local_json/person.json  #enables us to use anything in this folder

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Ubuntu
  #     fonts:
  #       - asset: fonts/Ubuntu-Light.ttf 
        # - asset: fonts/Ubuntu-Light.ttf

    
  

        
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

